# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QWidget(self.centralwidget)
        self.leftPanel.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanel.setFont(font)
        self.leftPanel.setStyleSheet("")
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLeftPanel = QtWidgets.QFrame(self.leftPanel)
        self.frameLeftPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeftPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeftPanel.setObjectName("frameLeftPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameLeftPanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.leftPanelButtonSearch = QtWidgets.QPushButton(self.frameLeftPanel)
        self.leftPanelButtonSearch.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonSearch.setFont(font)
        self.leftPanelButtonSearch.setObjectName("leftPanelButtonSearch")
        self.verticalLayout_2.addWidget(self.leftPanelButtonSearch)
        self.leftPanelButtonHome = QtWidgets.QPushButton(self.frameLeftPanel)
        self.leftPanelButtonHome.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonHome.setFont(font)
        self.leftPanelButtonHome.setObjectName("leftPanelButtonHome")
        self.verticalLayout_2.addWidget(self.leftPanelButtonHome)
        self.leftPanelButtonBibliotheque = QtWidgets.QPushButton(self.frameLeftPanel)
        self.leftPanelButtonBibliotheque.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonBibliotheque.setFont(font)
        self.leftPanelButtonBibliotheque.setObjectName("leftPanelButtonBibliotheque")
        self.verticalLayout_2.addWidget(self.leftPanelButtonBibliotheque)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frameLeftPanel)
        self.horizontalLayout.addWidget(self.leftPanel)
        self.centerPanel = QtWidgets.QVBoxLayout()
        self.centerPanel.setObjectName("centerPanel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.searchWidget = QtWidgets.QWidget()
        self.searchWidget.setStyleSheet("")
        self.searchWidget.setObjectName("searchWidget")
        self.layoutWidget = QtWidgets.QWidget(self.searchWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 831, 641))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayoutSearchWidget = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayoutSearchWidget.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutSearchWidget.setObjectName("gridLayoutSearchWidget")
        self.gridLayoutSearchBar = QtWidgets.QGridLayout()
        self.gridLayoutSearchBar.setContentsMargins(-1, 20, -1, 20)
        self.gridLayoutSearchBar.setObjectName("gridLayoutSearchBar")
        self.searchLabel = QtWidgets.QLabel(self.layoutWidget)
        self.searchLabel.setObjectName("searchLabel")
        self.gridLayoutSearchBar.addWidget(self.searchLabel, 0, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayoutSearchBar.addWidget(self.searchButton, 0, 2, 1, 1)
        self.searchLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayoutSearchBar.addWidget(self.searchLineEdit, 0, 1, 1, 1)
        self.gridLayoutSearchWidget.addLayout(self.gridLayoutSearchBar, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 827, 566))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.answerLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answerLabel.setGeometry(QtCore.QRect(80, 50, 271, 201))
        self.answerLabel.setText("")
        self.answerLabel.setObjectName("answerLabel")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayoutSearchWidget.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.searchWidget)
        self.homeWidget = QtWidgets.QWidget()
        self.homeWidget.setStyleSheet("")
        self.homeWidget.setObjectName("homeWidget")
        self.homeLabel = QtWidgets.QLabel(self.homeWidget)
        self.homeLabel.setGeometry(QtCore.QRect(380, 130, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.homeLabel.setFont(font)
        self.homeLabel.setStyleSheet("")
        self.homeLabel.setObjectName("homeLabel")
        self.stackedWidget.addWidget(self.homeWidget)
        self.bibliothequeWidget = QtWidgets.QWidget()
        self.bibliothequeWidget.setStyleSheet("")
        self.bibliothequeWidget.setObjectName("bibliothequeWidget")
        self.bibliothequeLabel = QtWidgets.QLabel(self.bibliothequeWidget)
        self.bibliothequeLabel.setGeometry(QtCore.QRect(290, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.bibliothequeLabel.setFont(font)
        self.bibliothequeLabel.setStyleSheet("")
        self.bibliothequeLabel.setObjectName("bibliothequeLabel")
        self.stackedWidget.addWidget(self.bibliothequeWidget)
        self.centerPanel.addWidget(self.stackedWidget)
        self.horizontalLayout.addLayout(self.centerPanel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.leftPanelButtonSearch.setText(_translate("MainWindow", "Rechercher"))
        self.leftPanelButtonHome.setText(_translate("MainWindow", "Acceuil"))
        self.leftPanelButtonBibliotheque.setText(_translate("MainWindow", "Bibliothèque"))
        self.searchLabel.setText(_translate("MainWindow", "Rechercher"))
        self.searchButton.setText(_translate("MainWindow", "Rechercher"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Tapez un nom de livre ici..."))
        self.homeLabel.setText(_translate("MainWindow", "HOME"))
        self.bibliothequeLabel.setText(_translate("MainWindow", "BIBLIOTHEQUE"))
