# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 0, 901, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.centerPanel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.centerPanel.setContentsMargins(0, 0, 0, 0)
        self.centerPanel.setObjectName("centerPanel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.searchWidget = QtWidgets.QWidget()
        self.searchWidget.setStyleSheet("")
        self.searchWidget.setObjectName("searchWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.searchWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 791, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.searchGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.searchGridLayout.setContentsMargins(0, 0, 0, 0)
        self.searchGridLayout.setObjectName("searchGridLayout")
        self.searchLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLabel.setFont(font)
        self.searchLabel.setStyleSheet("")
        self.searchLabel.setObjectName("searchLabel")
        self.searchGridLayout.addWidget(self.searchLabel, 0, 0, 1, 1)
        self.searchLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet("")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchGridLayout.addWidget(self.searchLineEdit, 0, 1, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.searchButton.setStyleSheet("")
        self.searchButton.setObjectName("searchButton")
        self.searchGridLayout.addWidget(self.searchButton, 0, 2, 1, 1)
        self.answerLabel = QtWidgets.QLabel(self.searchWidget)
        self.answerLabel.setGeometry(QtCore.QRect(170, 280, 461, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.answerLabel.setFont(font)
        self.answerLabel.setStyleSheet("")
        self.answerLabel.setText("")
        self.answerLabel.setObjectName("answerLabel")
        self.stackedWidget.addWidget(self.searchWidget)
        self.homeWidget = QtWidgets.QWidget()
        self.homeWidget.setStyleSheet("")
        self.homeWidget.setObjectName("homeWidget")
        self.homeLabel = QtWidgets.QLabel(self.homeWidget)
        self.homeLabel.setGeometry(QtCore.QRect(380, 130, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.homeLabel.setFont(font)
        self.homeLabel.setStyleSheet("")
        self.homeLabel.setObjectName("homeLabel")
        self.stackedWidget.addWidget(self.homeWidget)
        self.bibliothequeWidget = QtWidgets.QWidget()
        self.bibliothequeWidget.setStyleSheet("")
        self.bibliothequeWidget.setObjectName("bibliothequeWidget")
        self.bibliothequeLabel = QtWidgets.QLabel(self.bibliothequeWidget)
        self.bibliothequeLabel.setGeometry(QtCore.QRect(290, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.bibliothequeLabel.setFont(font)
        self.bibliothequeLabel.setStyleSheet("")
        self.bibliothequeLabel.setObjectName("bibliothequeLabel")
        self.stackedWidget.addWidget(self.bibliothequeWidget)
        self.centerPanel.addWidget(self.stackedWidget)
        self.leftPanel = QtWidgets.QWidget(self.centralwidget)
        self.leftPanel.setGeometry(QtCore.QRect(-1, -1, 201, 701))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanel.setFont(font)
        self.leftPanel.setStyleSheet("")
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.leftPanel)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 240, 201, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.leftPanelVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.leftPanelVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.leftPanelVerticalLayout.setObjectName("leftPanelVerticalLayout")
        self.leftPanelButtonHome = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonHome.setFont(font)
        self.leftPanelButtonHome.setObjectName("leftPanelButtonHome")
        self.leftPanelVerticalLayout.addWidget(self.leftPanelButtonHome)
        self.leftPanelButtonSearch = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonSearch.setFont(font)
        self.leftPanelButtonSearch.setObjectName("leftPanelButtonSearch")
        self.leftPanelVerticalLayout.addWidget(self.leftPanelButtonSearch)
        self.leftPanelButtonBibliotheque = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftPanelButtonBibliotheque.setFont(font)
        self.leftPanelButtonBibliotheque.setObjectName("leftPanelButtonBibliotheque")
        self.leftPanelVerticalLayout.addWidget(self.leftPanelButtonBibliotheque)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchLabel.setText(_translate("MainWindow", "Rechercher"))
        self.searchButton.setText(_translate("MainWindow", "Rechercher"))
        self.homeLabel.setText(_translate("MainWindow", "HOME"))
        self.bibliothequeLabel.setText(_translate("MainWindow", "BIBLIOTHEQUE"))
        self.leftPanelButtonHome.setText(_translate("MainWindow", "Acceuil"))
        self.leftPanelButtonSearch.setText(_translate("MainWindow", "Rechercher"))
        self.leftPanelButtonBibliotheque.setText(_translate("MainWindow", "Bibliothèque"))
